### ISSUE TITLE
On Paper 1.21.1, java.lang.NoSuchMethodException: org.bukkit.craftbukkit.inventory.CraftMetaSkull.setProfile(com.mojang.authlib.GameProfile)

### ISSUE THREAD

**Issue by Poikilos** [mehboss/CustomRecipes#58] opened 2024-10-03 23:22 UTC
### What happened?

...but the plugin works (and #55 and #56 fixed)

### What was supposed to happen?

Perform checks to provide compatibility across versions.

### How do I reproduce this issue?

```bash
1. Install plugin
2. Load server
3. Join server
```

### Relevant log output

https://pastebin.com/Vpd9cpPJ

### Server Version

Paper 1.21.1

### Plugin Version

1.9.2

### Server Mode

Online Mode

### Issue Confirmation

- [X] I have downloaded and tried the latest version of custom recipes and the issue still persists.
- [X] I have provided sufficient information for the issue to be replicated.

**Comment by mehboss** [comment] 2024-10-04 00:33
Recipe configuration that involves skulls please

**Comment by Poikilos** [comment] 2024-10-04 01:03
I don't have any skull recipes, but have the error on startup. I have the same recipes as before (Example: #55)

**Comment by mehboss** [comment] 2024-10-04 01:26
It seems to be an issue with my NBTEditor utility. I will look into this and get back to you soon. 

Thank you and apologies for the issue

**Comment by mehboss** [comment] 2024-10-06 01:32
Issue can not be reproduced once converting project to maven (will be released soon). Please open another ticket if problem persists, but I am unable to replicate this issue. 

Thank you

**Closed by mehboss** 2024-10-06 01:32 UTC
Labels: bug, confirmed
