### ISSUE TITLE
a small issue in book gui

### ISSUE THREAD

**Issue by MummieSenpai** [mehboss/CustomRecipes#6] opened 2023-06-25 13:08 UTC
**Server Version** paper-1.19.4-550.jar
**Plugin Version** CustomRecipes(v1.8).jar

**issue**
the book not showing the correct item used if a different custom recipe item is used. 
i made 2 recipes to compact redstone more the crafting aspect works  great. 
the issue at hand is if you look up the recipe it isnt pulling the data (enchanted glint, lore , name) from item identifier.
i tried using `name: '&aEnchanted Redstone dust'` in the crafting material section to force the name. 
the color code isnt applied if you hover over the name. 
![javaw_HbardPf9bi](https://github.com/mehboss/CustomRecipes/assets/28273585/23abca6b-e723-4a5b-8360-55d448f72ec3)
the wiki states @ 18. Ingredients
it supports color codes. while it does not.

unless i missed something this is an small bug. 

the 2 crafting configs in this [hastebin](https://hastebin.com/share/kufeteruxe.yaml)

**Comment by mehboss** [comment] 2023-06-25 17:17
Hello!
Thank you for bringing this to my attention. I will have this issue resolved within the next hour or two. I'll let you know when it is resolved

Thanks,
Mehboss

**Comment by MummieSenpai** [comment] 2023-06-25 17:24
thank you for the fast response. 
is there a way to have the plugin pull the info of the custom item made with a custom  crafting recipe ? using the identifier

**Comment by mehboss** [comment] 2023-06-25 17:54
In the GUI? Yes. That is how it was intended to be in the GUI book, but I unfortunately forgot to set that portion up.

**Comment by mehboss** [comment] 2023-06-25 18:33
Hello again! Thank you for reporting this issue. I am proud to say that it has been resolved now. The update can be found [here.](https://www.spigotmc.org/resources/%E2%96%BA%E2%96%BA-custom-crafting-recipes-1-8-x-1-20-x-per-recipe-perms-create-your-own-recipes-%E2%97%84%E2%97%84.36925/update?update=505927) If you encounter any other issues please open up another ticket. If you have any feature suggestions feel free to let me know!

Report closed w/ status of resolved.

Thanks,
Mehboss.

**Closed by mehboss** 2023-06-25 18:33 UTC
Labels: bug
