### ISSUE TITLE
[Question]: ErrorLog

### ISSUE THREAD

**Issue by BellCocoa** [mehboss/CustomRecipes#35] opened 2023-09-05 18:30 UTC
It is running on mohist due to its configuration.

I get an error after starting with 1.19.2. No response when typing commands.

Entered using DeepL.
https://pastebin.com/q98F1mzi

**Comment by mehboss** [comment] 2023-09-05 18:58
Hello there,
I ask that when opening an issue you click "New Issue" and then "Bug Report". Furthermore, more information is needed to assist you. Can you provide me with your recipe files? Looking at the error, it seems that there is an issue with one of the recipe material types as the error indicates one may be set to AIR.

Thank you,
Mehboss.

**Comment by BellCocoa** [comment] 2023-09-05 19:03
No recipes have been added yet. Default recipe.

**Comment by mehboss** [comment] 2023-09-05 19:07
Hello again,
Can you confirm that the recipe files were generated when you initially imported the plugin and started your server? Also, what are you using and what version? (examples are spigot, paperspigot, purpur, bukkit, etc). Finally, what version of Java is your server running on?

Thank you

**Comment by mehboss** [comment] 2023-09-05 19:11
One other request, could you send me a list of all of your active plugins? There may be a conflict with another crafting plugin.

Thank you

**Comment by BellCocoa** [comment] 2023-09-05 19:16
We use mohist, which allows forge and plugin to coexist.
Recipe file will be generated when launched
Java version is 17.0.2

I only included LuckPerms.

**Comment by mehboss** [comment] 2023-09-05 19:19
So the only plugin you are running is LuckPerms? And sorry, you said no recipe files have been generated yet? And you are not running Spigot or Paper, you are running forge?

**Comment by mehboss** [comment] 2023-09-05 19:20
![Uploading image.png…]()
I would recommend contacting MohistMC, as it seems they may need to implement support for it.

**Comment by BellCocoa** [comment] 2023-09-05 19:24
I have only included LuckPerms.

Recipe is generated when launched

**Comment by mehboss** [comment] 2023-09-05 19:26
I unfortunately am unable to reproduce this issue. CustomRecipes has been tested on all versions of Spigot and Paper and will work on Purpur as well. I have not encountered this issue from anyone else, including myself.

![image](https://github.com/mehboss/CustomRecipes/assets/17992070/5450ce79-1fa2-4b43-8424-954ab94764e6)

I will leave this ticket open for further investigation, but I would highly recommend contacting Mohist via their discord server or by opening a github ticket so they can assist you. I believe the issue is caused by the server host and not the plugin itself. The originating line of error should not be causing any errors (Line #350 in Main class).

Let me know what they say after you have contacted Mohist support

Thank you,
Mehboss.

**Comment by BellCocoa** [comment] 2023-09-05 19:27
I understand. I'll try to contact you.

**Comment by mehboss** [comment] 2023-09-06 21:14
Hello again,
I have heard back from Mohist discord support and this is what they said:
"Since Mohist-1.19.2 is still in the development stage, there are still many issues"

I am closing this ticket with a result of "can't fix" because resolution must be done through Mohist support or by opening a github ticket on their github site.

I apologize for the inconvenience.
Thank you,
Mehboss.

**Closed by mehboss** 2023-09-06 21:14 UTC
Labels: bug, unconfirmed
