### ISSUE TITLE
Error purpur 1.21.1

### ISSUE THREAD

**Issue by Dawlnken** [mehboss/CustomRecipes#63] opened 2024-12-18 18:35 UTC
### What happened?

A huge error shows up in console, the item crafts normally but there is massive console spam every time I craft a custom item.

### What was supposed to happen?

No erros, clean console.

### How do I reproduce this issue?

```bash
1. Install plugin on Purpur 1.21.1-2329-803bf62 (MC: 1.21.1)
2. Create any custom item using a crafting table.
3. See spam in console.
...
```

### Relevant log output

```shell
java.lang.IllegalArgumentException: Cannot translate null text
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:356) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at CustomRecipes-1.9.8.jar/me.mehboss.utils.RecipeUtil$Ingredient.getDisplayName(RecipeUtil.java:752) ~[CustomRecipes-1.9.8.jar:?]
	at CustomRecipes-1.9.8.jar/me.mehboss.crafting.CraftManager.validateItem(CraftManager.java:140) ~[CustomRecipes-1.9.8.jar:?]
	at CustomRecipes-1.9.8.jar/me.mehboss.crafting.CraftManager.amountsMatch(CraftManager.java:173) ~[CustomRecipes-1.9.8.jar:?]
	at CustomRecipes-1.9.8.jar/me.mehboss.crafting.CraftManager.handleCrafting(CraftManager.java:674) ~[CustomRecipes-1.9.8.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:44) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2329-803bf62]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPreCraftEvent(CraftEventFactory.java:1464) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.inventory.CraftingMenu.slotChangedCraftingGrid(CraftingMenu.java:98) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.inventory.CraftingMenu.lambda$slotsChanged$0(CraftingMenu.java:110) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.inventory.ContainerLevelAccess.lambda$execute$0(ContainerLevelAccess.java:85) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.inventory.ContainerLevelAccess$2.evaluate(ContainerLevelAccess.java:72) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.inventory.ContainerLevelAccess.execute(ContainerLevelAccess.java:84) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.inventory.CraftingMenu.slotsChanged(CraftingMenu.java:109) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.inventory.TransientCraftingContainer.setItem(TransientCraftingContainer.java:147) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.inventory.Slot.set(Slot.java:66) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.inventory.Slot.setByPlayer(Slot.java:62) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.inventory.Slot.setByPlayer(Slot.java:58) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.inventory.Slot.safeInsert(Slot.java:134) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.inventory.AbstractContainerMenu.doClick(AbstractContainerMenu.java:557) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.inventory.AbstractContainerMenu.clicked(AbstractContainerMenu.java:383) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3314) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3237) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1581) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1558) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1551) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1510) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1517) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1362) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[14:27:35] [Server thread/ERROR]: Could not pass event CraftItemEvent to CustomRecipes v1.9.8
java.lang.IllegalArgumentException: Cannot translate null text
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:356) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at CustomRecipes-1.9.8.jar/me.mehboss.utils.RecipeUtil$Ingredient.getDisplayName(RecipeUtil.java:752) ~[CustomRecipes-1.9.8.jar:?]
	at CustomRecipes-1.9.8.jar/me.mehboss.crafting.AmountManager.handleShiftClicks(AmountManager.java:201) ~[CustomRecipes-1.9.8.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:44) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2329-803bf62]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3306) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1581) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1558) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1551) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1673) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1342) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Relevant file configuration

```shell
recipe 1: https://pastebin.com/XUMz8M33
recipe 2: https://pastebin.com/Y2GBzLUr
recipe 3: https://pastebin.com/eVmffvxm

Plugins list:

[15:27:49 INFO]: Paper Plugins: (0):
[15:27:49 INFO]: Bukkit Plugins: (7):
[15:27:49 INFO]:  - BungeeGuard, CustomRecipes, Essentials, LuckPerms, Vault, ViaBackwards, ViaVersion
```

### Server Version

Purpur 1.21.1-2329-803bf62 (MC: 1.21.1)

### Plugin Version

 CustomRecipes version 1.9.8

### Server Mode

Offline Mode

### Issue Confirmation

- [X] I have downloaded and tried the latest version of custom recipes and the issue still persists.
- [X] I have provided sufficient information for the issue to be replicated.

**Comment by mehboss** [comment] 2024-12-18 18:56
Hello there,
The issue is caused from your recipe file(s) missing the recipe “Name” section. This is unintended and will be fixed this afternoon. My apologies. You will be notified when I release the fix. 

Thank you

**Comment by mehboss** [comment] 2024-12-19 20:49
I believe the issue has been resolved. I have done some testing to ensure there were no errors in console and that the recipes were functioning properly.

See the update here:
https://www.spigotmc.org/resources/%E2%96%BA%E2%96%BA-customrecipes-1-8-x-1-21-x-advanced-recipes-made-easy-%E2%97%84%E2%97%84.36925/update?update=573333

Thank you for reporting, and for being patient.

**Closed by mehboss** 2024-12-19 20:49 UTC
Labels: 🐞 Bug, ✓ Confirmed
